[package]
name = "drlogseeker"
version = "0.1.0"
edition = "2024"
authors = ["loxoron218"]
description = "An application for analyzing DR values in log files"

[dependencies]
gio = "*"
glib = "*"
gtk4 = "*"
libadwaita = "*"
regex = "*"
tokio = { version = "*", features = ["full"] }
